version: 2

sources:
  - name: external
    database: CT_PRIYANSH_MATHUR_DB
    schema: EXTERNAL
    config:
      freshness:
        warn_after:
          count: 7
          period: day
        error_after:
          count: 12
          period: day
    tables:
      - name: EXT_CAMPAIGNS
      - name: EXT_CUSTOMERS
      - name: EXT_EMPLOYEES
      - name: EXT_ORDERS
      - name: EXT_PRODUCTS
      - name: EXT_STORES
      - name: EXT_SUPPLIERS